<h1 style="text-align:center;color:black;background-color:#6C757D;padding:10px;border-radius:8px;font-size:28px;">Agricultural Wages</h1>

 # Dataset Overview & Introduction
This dataset contains 500 records and 14 columns detailing rural agricultural wage metrics across different regions, states, districts, and collection centers. It captures temporal, spatial, and demographic data—including labor categories, specific agricultural work types, gender breakdowns, and both monthly and annual average wages.   


## 2. Dataset Schema & Structure
The dataset (`Agricultural_Wages_Sample_Data.csv`) contains **500 records** and **14 columns** structured as follows:

| Column Name | Description |
| :--- | :--- |
| **Date (month)** | Recording month and year |
| **State Name / Code** | State or Union Territory identification |
| **District Name / Code** | District-level geographic mapping |
| **Center Name / Code** | Data collection center and coordinates (Latitude/Longitude) |
| **Category & Type of Labour** | Classification of agricultural work tasks |
| **Gender of Labour** | Workforce demographic categorization |
| **Monthly & Annual Wages** | Financial wage metrics |

---

## 3. Analysis Objectives
1. **Data Inspection & Preprocessing:** Verify data types, check for missing or null values, and clean the dataset.
2. **Univariate Analysis:** Explore wage distributions, labor types, and geographic spreads.
3. **Bivariate & Comparative Analysis:** Evaluate wage disparities across states, labor categories, and demographic groups.
4. **Visualizations:** Generate clean charts and plots to highlight key trends in agricultural wages.

In [371]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Imports the library, which is the core tool for data manipulation and analysis.

In [372]:
#  Load the CSV file into a DataFrame

df = pd.read_csv("Agricultural Wages_Sample_Data.csv")

In [373]:
 # Display the first 10 rows of the data

df.head(10)

,Date (month),State Name (state_name),State Code (state_code),District Name (district_name),District Code (district_code),Center Name (center_name),Center Code (center_code),Latitude (latitude),Longitude (longitude),Category of labour (labour_category),Labour work engaged in (labour_type),Gender of Labour (gender),Average monthly wage (monthly_average_wage),Annual average wage (annual_average_wage)
0,2019-05-01,Assam,18,Hailakandi,289,Bolipara,177007,24.679855,92.560924,Other Agricultural Labour,Other Agricultural Labour,Women,0.0,264.29
1,2017-06-01,Odisha,21,Boudh,349,Boudh,128114,20.838590,84.322360,Field Labour,Sower,Women,150.0,157.00
2,2015-03-01,Kerala,32,Kozhikode,561,Koduvally,143706,11.360150,75.910840,Field Labour,Weeder,Women,460.0,453.33
3,2017-01-01,Tamil Nadu,33,Madurai,578,Katchirairuppu,900960,0.000000,0.000000,Skilled Labour,Blacksmith,Men,0.0,600.00
4,2014-10-01,Rajasthan,8,Barmer,90,Kuseep,197443,25.683451,72.304800,Field Labour,Weeder,Men,300.0,300.00
5,2011-11-01,Odisha,21,Boudh,349,Boudh,128114,20.838590,84.322360,Herdsmen,Herdsmen,Men,120.0,118.00
6,2019-06-01,Madhya Pradesh,23,Jabalpur,411,Patan,901072,23.850700,72.129630,Field Labour,Sower,Men,160.0,158.57
7,2018-08-01,Madhya Pradesh,23,Khargone,414,Gaugao,901054,0.000000,0.000000,Field Labour,Ploughman,Women,0.0,0.00
8,2020-02-01,Gujarat,24,Morbi,673,Morbi,10507,22.807770,70.823560,Field Labour,Weeder,Women,180.0,224.55
9,2014-03-01,Punjab,3,Moga,38,Nathoke,199924,0.000000,0.000000,Field Labour,Weeder,Men,0.0,290.00

In [374]:
# Display the last 5 rows

df.tail()

,Date (month),State Name (state_name),State Code (state_code),District Name (district_name),District Code (district_code),Center Name (center_name),Center Code (center_code),Latitude (latitude),Longitude (longitude),Category of labour (labour_category),Labour work engaged in (labour_type),Gender of Labour (gender),Average monthly wage (monthly_average_wage),Annual average wage (annual_average_wage)
495,2012-06-01,Himachal Pradesh,2,Shimla,23,Shimla,143022,31.10321,77.15847,Skilled Labour,Carpenter,Women,0.0,0.00
496,2015-08-01,Odisha,21,Nuapada,368,Naupada,115268,0.00000,0.00000,Skilled Labour,Blacksmith,Men,200.0,264.17
497,2015-08-01,Telangana,36,Adilabad,501,Indravalli,101513,19.66021,78.64248,Skilled Labour,Cobbler,Men,160.0,158.82
498,2011-08-01,Gujarat,24,Vadodara,461,Karjan,124699,22.05137,73.11858,Skilled Labour,Blacksmith,Women,0.0,0.00
499,2014-07-01,Rajasthan,8,Dausa,97,Koliwara,114936,26.68532,76.34071,Field Labour,Sower,Men,350.0,350.00

In [375]:
# it shows the rows and columns

df.shape

(500, 14)

In [376]:
# An integer representing the total number of elements/cells in the entire DataFrame.

df.size

7000

In [377]:
df.columns

Index(['Date (month)', 'State Name (state_name)', 'State Code (state_code)',
       'District Name (district_name)', 'District Code (district_code)',
       'Center Name (center_name)', 'Center Code (center_code)',
       'Latitude (latitude)', 'Longitude (longitude)',
       'Category of labour (labour_category)',
       'Labour work engaged in (labour_type)', 'Gender of Labour (gender)',
       'Average monthly wage (monthly_average_wage)',
       'Annual average wage (annual_average_wage)'],
      dtype='str')

It returns an Index object containing the names of all the columns in your dataset.

In [378]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [379]:
df.columns

Index(['date_(month)', 'state_name_(state_name)', 'state_code_(state_code)',
       'district_name_(district_name)', 'district_code_(district_code)',
       'center_name_(center_name)', 'center_code_(center_code)',
       'latitude_(latitude)', 'longitude_(longitude)',
       'category_of_labour_(labour_category)',
       'labour_work_engaged_in_(labour_type)', 'gender_of_labour_(gender)',
       'average_monthly_wage_(monthly_average_wage)',
       'annual_average_wage_(annual_average_wage)'],
      dtype='str')

Removes any accidental blank spaces at the very beginning or end of the column names,Converts all capital letters to small letters (lowercase). This ensures uniformity so you don't have to worry about uppercase/lowercase mistakes later,Finds any spaces between the words in the column names and replaces them with an underscore (_).

In [380]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 14 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   date_(month)                                 500 non-null    str
 1   state_name_(state_name)                      500 non-null    str
 2   state_code_(state_code)                      500 non-null    int64
 3   district_name_(district_name)                500 non-null    str
 4   district_code_(district_code)                500 non-null    int64
 5   center_name_(center_name)                    500 non-null    str
 6   center_code_(center_code)                    500 non-null    int64
 7   latitude_(latitude)                          500 non-null    float64
 8   longitude_(longitude)                        500 non-null    float64
 9   category_of_labour_(labour_category)         500 non-null    str
 10  labour_work_engaged_in_(labour_type)         500 non-null    str
 11  gender_of_labour_(gender)                    500 non-null    str
 12  average_monthly_wage_(monthly_average_wage)  500 non-null    float64
 13  annual_average_wage_(annual_average_wage)    500 non-null    float64
dtypes: float64(4), int64(3), str(7)
memory usage: 54.8 KB

The df.info() method is one of the most important and frequently used commands in Pandas. It provides a concise summary of your DataFrame's structure, data types, and memory usage.

In [381]:
df.dtypes

date_(month)                                       str
state_name_(state_name)                            str
state_code_(state_code)                          int64
district_name_(district_name)                      str
district_code_(district_code)                    int64
center_name_(center_name)                          str
center_code_(center_code)                        int64
latitude_(latitude)                            float64
longitude_(longitude)                          float64
category_of_labour_(labour_category)               str
labour_work_engaged_in_(labour_type)               str
gender_of_labour_(gender)                          str
average_monthly_wage_(monthly_average_wage)    float64
annual_average_wage_(annual_average_wage)      float64
dtype: object

The df.dtypes attribute is used to check the data type of every column in your DataFrame.

In [382]:
df.describe(include="all")

,date_(month),state_name_(state_name),state_code_(state_code),district_name_(district_name),district_code_(district_code),center_name_(center_name),center_code_(center_code),latitude_(latitude),longitude_(longitude),category_of_labour_(labour_category),labour_work_engaged_in_(labour_type),gender_of_labour_(gender),average_monthly_wage_(monthly_average_wage),annual_average_wage_(annual_average_wage)
count,500,500,500.000000,500,500.000000,500,500.000000,500.000000,500.000000,500,500,500,500.000000,500.00000
unique,117,21,NaN,305,NaN,371,NaN,NaN,NaN,4,10,2,NaN,NaN
top,2019-10-01,Madhya Pradesh,NaN,Kozhikode,NaN,Boudh,NaN,NaN,NaN,Field Labour,Other Agricultural Labour,Women,NaN,NaN
freq,14,75,NaN,5,NaN,4,NaN,NaN,NaN,231,73,260,NaN,NaN
mean,NaN,NaN,18.516000,NaN,333.702000,NaN,429641.754000,15.266557,53.216134,NaN,NaN,NaN,137.189200,189.39106
std,NaN,NaN,8.765124,NaN,177.036576,NaN,367444.780148,11.518437,38.185512,NaN,NaN,NaN,161.030039,155.00947
min,NaN,NaN,2.000000,NaN,17.000000,NaN,10507.000000,0.000000,0.000000,NaN,NaN,NaN,0.000000,0.00000
25%,NaN,NaN,9.000000,NaN,177.000000,NaN,140968.500000,0.000000,0.000000,NaN,NaN,NaN,0.000000,0.00000
50%,NaN,NaN,21.000000,NaN,361.500000,NaN,181611.500000,20.360370,76.115670,NaN,NaN,NaN,100.000000,185.83500
75%,NaN,NaN,23.000000,NaN,440.250000,NaN,900634.500000,24.563709,81.949705,NaN,NaN,NaN,250.000000,300.00000
max,NaN,NaN,36.000000,NaN,704.000000,NaN,901072.000000,31.709200,94.891000,NaN,NaN,NaN,753.000000,779.17000

Generates a complete statistical summary for all columns in your DataFrame (numerical, categorical text, and datetime columns).

DATA CLEANING

In [383]:
df.isnull().sum()

date_(month)                                   0
state_name_(state_name)                        0
state_code_(state_code)                        0
district_name_(district_name)                  0
district_code_(district_code)                  0
center_name_(center_name)                      0
center_code_(center_code)                      0
latitude_(latitude)                            0
longitude_(longitude)                          0
category_of_labour_(labour_category)           0
labour_work_engaged_in_(labour_type)           0
gender_of_labour_(gender)                      0
average_monthly_wage_(monthly_average_wage)    0
annual_average_wage_(annual_average_wage)      0
dtype: int64

Checks every column in your DataFrame for missing (null) values and counts them.
output shows 0 missing values across all columns, it means dataset is completely clean with no null or empty data entries.

In [384]:
df.duplicated().sum()

np.int64(0)

The output np.int64(0) indicates that there are zero duplicate rows in your dataset, meaning every single row is completely unique.

In [385]:
df['category_of_labour_(labour_category)'].unique()

<StringArray>
['Other Agricultural Labour', 'Field Labour', 'Skilled Labour', 'Herdsmen']
Length: 4, dtype: str

Shows all unique values

In [386]:
df['date_(month)'] = pd.to_datetime(df['date_(month)'])

Converts the data type of the date_(month) column from a plain string/text object (object) into a standard Pandas datetime format (datetime64).

Exploratory Data Analysis (EDA)

In [388]:
df['year'] = df['date_(month)'].dt.year
df['month'] = df['date_(month)'].dt.month

created year,month seperate columns

In [390]:
df['latitude_(latitude)'] = df['latitude_(latitude)'].replace(0.0, None)
df['longitude_(longitude)'] = df['longitude_(longitude)'].replace(0.0, None)
df['latitude_(latitude)'] = df['latitude_(latitude)'].ffill()
df['longitude_(longitude)'] = df['longitude_(longitude)'].ffill()

Replaces invalid 0.0 coordinates in the latitude and longitude columns with missing values (None), and then fills those gaps using the previous valid value (ffill).

In [392]:
df['average_monthly_wage_(monthly_average_wage)'] = df['average_monthly_wage_(monthly_average_wage)'].replace(0.0, None)
df['annual_average_wage_(annual_average_wage)'] = df['annual_average_wage_(annual_average_wage)'].replace(0.0, None)

monthly_median= df['average_monthly_wage_(monthly_average_wage)'].median()
df['average_monthly_wage_(monthly_average_wage)'] = df['average_monthly_wage_(monthly_average_wage)'].fillna(monthly_median)

df['annual_average_wage_(annual_average_wage)']=df['annual_average_wage_(annual_average_wage)'].fillna(df['average_monthly_wage_(monthly_average_wage)']*12)

In [395]:
df.head(10)

,date_(month),state_name_(state_name),state_code_(state_code),district_name_(district_name),district_code_(district_code),center_name_(center_name),center_code_(center_code),latitude_(latitude),longitude_(longitude),category_of_labour_(labour_category),labour_work_engaged_in_(labour_type),gender_of_labour_(gender),average_monthly_wage_(monthly_average_wage),annual_average_wage_(annual_average_wage),year,month
0,2019-05-01,Assam,18,Hailakandi,289,Bolipara,177007,24.679855,92.560924,Other Agricultural Labour,Other Agricultural Labour,Women,250.0,264.29,2019,5
1,2017-06-01,Odisha,21,Boudh,349,Boudh,128114,20.83859,84.32236,Field Labour,Sower,Women,150.0,157.0,2017,6
2,2015-03-01,Kerala,32,Kozhikode,561,Koduvally,143706,11.36015,75.91084,Field Labour,Weeder,Women,460.0,453.33,2015,3
3,2017-01-01,Tamil Nadu,33,Madurai,578,Katchirairuppu,900960,11.36015,75.91084,Skilled Labour,Blacksmith,Men,250.0,600.0,2017,1
4,2014-10-01,Rajasthan,8,Barmer,90,Kuseep,197443,25.683451,72.3048,Field Labour,Weeder,Men,300.0,300.0,2014,10
5,2011-11-01,Odisha,21,Boudh,349,Boudh,128114,20.83859,84.32236,Herdsmen,Herdsmen,Men,120.0,118.0,2011,11
6,2019-06-01,Madhya Pradesh,23,Jabalpur,411,Patan,901072,23.8507,72.12963,Field Labour,Sower,Men,160.0,158.57,2019,6
7,2018-08-01,Madhya Pradesh,23,Khargone,414,Gaugao,901054,23.8507,72.12963,Field Labour,Ploughman,Women,250.0,3000.0,2018,8
8,2020-02-01,Gujarat,24,Morbi,673,Morbi,10507,22.80777,70.82356,Field Labour,Weeder,Women,180.0,224.55,2020,2
9,2014-03-01,Punjab,3,Moga,38,Nathoke,199924,22.80777,70.82356,Field Labour,Weeder,Men,250.0,290.0,2014,3

Replaces erroneous 0.0 values in both monthly and annual wage columns with NaN, fills missing monthly wages using the column's median, and correctly computes the corresponding annual wages (monthly wage * 12) to ensure full data integrity.

In [ ]:
bins = [0, 200, 500, df['average_monthly_wage_(monthly_average_wage)'].max()]
labels = ['Low Wage', 'Medium Wage', 'High Wage']
df['wage_category'] = pd.cut(df['average_monthly_wage_(monthly_average_wage)'], bins=bins, labels=labels)

In [397]:
df[['average_monthly_wage_(monthly_average_wage)', 'wage_category']].head(10)

  average_monthly_wage_(monthly_average_wage) wage_category
0                                       250.0   Medium Wage
1                                       150.0      Low Wage
2                                       460.0   Medium Wage
3                                       250.0   Medium Wage
4                                       300.0   Medium Wage
5                                       120.0      Low Wage
6                                       160.0      Low Wage
7                                       250.0   Medium Wage
8                                       180.0      Low Wage
9                                       250.0   Medium Wage

In [398]:
print(df['wage_category'].value_counts())

wage_category
Medium Wage    386
Low Wage       104
High Wage       10
Name: count, dtype: int64

Segments continuous monthly wages into discrete bins (0–200, 200–500, and up to the maximum value) and assigns readable labels (Low Wage, Medium Wage, High Wage).

In [399]:
df.columns

Index(['date_(month)', 'state_name_(state_name)', 'state_code_(state_code)',
       'district_name_(district_name)', 'district_code_(district_code)',
       'center_name_(center_name)', 'center_code_(center_code)',
       'latitude_(latitude)', 'longitude_(longitude)',
       'category_of_labour_(labour_category)',
       'labour_work_engaged_in_(labour_type)', 'gender_of_labour_(gender)',
       'average_monthly_wage_(monthly_average_wage)',
       'annual_average_wage_(annual_average_wage)', 'year', 'month',
       'wage_category'],
      dtype='str')

In [404]:
pivot_df = df.pivot_table(
    index='state_code_(state_code)', 
    columns='category_of_labour_(labour_category)', 
    values='average_monthly_wage_(monthly_average_wage)', 
    aggfunc='mean'
)
print(pivot_df)

category_of_labour_(labour_category) Field Labour    Herdsmen  \
state_code_(state_code)
2                                           156.0       100.0
3                                      259.166667         NaN
5                                           320.0       300.0
6                                      309.090909         NaN
8                                      273.931034       255.0
9                                           234.0         NaN
10                                         261.25       195.0
16                                            NaN         NaN
18                                          275.0       250.0
19                                     213.833333       180.0
20                                          249.0       250.0
21                                      230.47619  202.857143
22                                     233.529412       212.0
23                                     235.428571  241.666667
24                                     201.357143       200.0
27                                            NaN       250.0
28                                          246.5       250.0
29                                          210.0       350.0
32                                     402.777778         NaN
33                                     194.327273         NaN
36                                          230.0       275.0

category_of_labour_(labour_category) Other Agricultural Labour Skilled Labour
state_code_(state_code)
2                                                        221.0          250.0
3                                                        250.0          250.0
5                                                        400.0     366.666667
6                                                          NaN     366.666667
8                                                          NaN     310.714286
9                                                        230.0     303.571429
10                                                       237.5          250.0
16                                                       275.0            NaN
18                                                       226.0          315.0
19                                                       250.0          250.0
20                                                       212.5          230.0
21                                                  276.111111     301.111111
22                                                       180.0     273.333333
23                                                  233.333333     282.857143
24                                                       142.0          263.1
27                                                         NaN          400.0
28                                                  332.142857          250.0
29                                                       355.0          275.0
32                                                      500.75     291.666667
33                                                      224.75     273.666667
36                                                       250.0     251.666667

Transforms the cleaned dataset into an Excel-style matrix format to easily compare average monthly wages across different states and labour categories.

Code:

In [408]:
df.groupby([
    'labour_work_engaged_in_(labour_type)', 
    'gender_of_labour_(gender)'
])[['average_monthly_wage_(monthly_average_wage)']].mean().reset_index()

,labour_work_engaged_in_(labour_type),gender_of_labour_(gender),average_monthly_wage_(monthly_average_wage)
0,Blacksmith,Men,317.947368
1,Blacksmith,Women,250.0
2,Carpenter,Men,358.925926
3,Carpenter,Women,250.0
4,Cobbler,Men,285.882353
5,Cobbler,Women,250.0
6,Field Labour,Men,268.0
7,Field Labour,Women,232.727273
8,Herdsmen,Men,240.384615
9,Herdsmen,Women,220.740741
10,Other Agricultural Labour,Men,270.625
11,Other Agricultural Labour,Women,243.181818
12,Ploughman,Men,260.62963
13,Ploughman,Women,250.0
14,Reaper & Harvester,Men,280.0
15,Reaper & Harvester,Women,241.166667
16,Sower,Men,270.533333
17,Sower,Women,222.366667
18,Weeder,Men,247.96
19,Weeder,Women,234.576471

Groups the dataset by specific labour tasks (labour_work_engaged_in_(labour_type)) and gender (gender_of_labour_(gender)) to evaluate and compare average monthly wages across different work roles and demographics.

In [409]:
df.groupby([
    'year', 
    'state_code_(state_code)'
])[['average_monthly_wage_(monthly_average_wage)']].mean().reset_index()

     year  state_code_(state_code) average_monthly_wage_(monthly_average_wage)
0    2010                        2                                       200.0
1    2010                        3                                       250.0
2    2010                        8                                       250.0
3    2010                       10                                       250.0
4    2010                       18                                       250.0
..    ...                      ...                                         ...
162  2020                       28                                       425.0
163  2020                       29                                       350.0
164  2020                       32                                       250.0
165  2020                       33                                       337.5
166  2020                       36                                       250.0

[167 rows x 3 columns]

Groups the dataset by time (year) and geographic location (state_code_(state_code)) to analyze year-over-year wage trends across different states.